# Generated by Django 4.0.4 on 2022-07-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number', models.PositiveSmallIntegerField()),
                ('url', models.URLField()),
                ('transcript', models.TextField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
