# Generated by Django 4.0.4 on 2022-05-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
