# Generated by Django 4.0.8 on 2022-12-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynchnumbers', '0002_alter_number_number_alter_number_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={'get_latest_by': 'date', 'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='number',
            name='id',
        ),
        migrations.AlterField(
            model_name='number',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
