# Generated by Django 4.0.8 on 2023-02-04 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynchnumbers', '0004_rename_transcript_number_yt_video_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='yt_video_id',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='[\\w\\-]{11}')], verbose_name='YouTube Video ID'),
        ),
        migrations.AlterField(
            model_name='number',
            name='yt_video_transcript',
            field=models.TextField(verbose_name='YouTube Video Transcript'),
        ),
    ]
