# Generated by Django 4.0.8 on 2023-02-04 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynchnumbers', '0005_alter_number_yt_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='yt_video_id',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[\\w\\-]{11}$')], verbose_name='YouTube Video ID'),
        ),
    ]
