# Generated by Django 4.0.8 on 2023-02-05 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lynchnumbers', '0006_alter_number_yt_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='yt_video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='lynchvideos', verbose_name='YouTube Video'),
            preserve_default=False,
        ),
    ]
